// data_es.js - Tabla Periódica Completa en Español (118 elementos)
// Fuente: Datos estándar IUPAC + traducciones y descripciones generadas para educación
const elementos = [
  {
    "name": "Hidrógeno",
    "symbol": "H",
    "number": 1,
    "atomic_mass": 1.008,
    "category": "no-metal",
    "melt": 13.99,
    "boil": 20.271,
    "density": 0.08988,
    "discovered_by": "Henry Cavendish",
    "group": 1,
    "period": 1,
    "xpos": 1,
    "ypos": 1,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Hydrogenglow.jpg/200px-Hydrogenglow.jpg", "title": "Hidrógeno gaseoso"},
    "desc_es": "El elemento más abundante en el universo (75% de la masa bariónica). Gas incoloro, inodoro e insípido. Se encuentra en estrellas y planetas; usado en cohetes y fertilizantes."
  },
  {
    "name": "Helio",
    "symbol": "He",
    "number": 2,
    "atomic_mass": 4.0026,
    "category": "gas-noble",
    "melt": 0.95,
    "boil": 4.222,
    "density": 0.1786,
    "discovered_by": "Pierre Janssen",
    "group": 18,
    "period": 1,
    "xpos": 18,
    "ypos": 1,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Helium_discharge_tube.jpg/200px-Helium_discharge_tube.jpg", "title": "Tubo de descarga de helio"},
    "desc_es": "Segundo elemento más abundante. Gas inerte ligero, se encuentra en el Sol y gas natural. Usado en globos meteorológicos y enfriamiento de imanes superconductores."
  },
  {
    "name": "Litio",
    "symbol": "Li",
    "number": 3,
    "atomic_mass": 6.94,
    "category": "alcalino",
    "melt": 453.65,
    "boil": 1603,
    "density": 0.534,
    "discovered_by": "Johan Arfwedson",
    "group": 1,
    "period": 2,
    "xpos": 1,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lithium.jpg/200px-Lithium.jpg", "title": "Litio metálico"},
    "desc_es": "Metal alcalino blando, plateado. Se encuentra en minerales como espodumena. Esencial en baterías de ion-litio para celulares y autos eléctricos."
  },
  {
    "name": "Berilio",
    "symbol": "Be",
    "number": 4,
    "atomic_mass": 9.0122,
    "category": "alcalinoterreo",
    "melt": 1560,
    "boil": 2742,
    "density": 1.85,
    "discovered_by": "Louis Nicolas Vauquelin",
    "group": 2,
    "period": 2,
    "xpos": 2,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Beryllium.jpg/200px-Beryllium.jpg", "title": "Berilio cristalino"},
    "desc_es": "Metal duro, gris y ligero. Se encuentra en berilo (piedra preciosa). Usado en aleaciones para aviones y satélites por su rigidez."
  },
  {
    "name": "Boro",
    "symbol": "B",
    "number": 5,
    "atomic_mass": 10.81,
    "category": "metaloides",
    "melt": 2349,
    "boil": 4200,
    "density": 2.08,
    "discovered_by": "Joseph Louis Gay-Lussac",
    "group": 13,
    "period": 2,
    "xpos": 13,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Boron.jpg/200px-Boron.jpg", "title": "Cristales de boro"},
    "desc_es": "Semimetal negro o marrón. Se encuentra en borax natural. Usado en vidrio Pyrex, fertilizantes y semiconductores."
  },
  {
    "name": "Carbono",
    "symbol": "C",
    "number": 6,
    "atomic_mass": 12.011,
    "category": "no-metal",
    "melt": 3823,
    "boil": 4098,
    "density": 2.26,
    "discovered_by": "Antiguo",
    "group": 14,
    "period": 2,
    "xpos": 14,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Graphite-3D-balls.png/200px-Graphite-3D-balls.png", "title": "Estructura de grafito"},
    "desc_es": "Base de toda la vida orgánica. Se encuentra en diamantes, grafito y fullerenos. Usado en acero, plásticos y nanotecnología."
  },
  {
    "name": "Nitrógeno",
    "symbol": "N",
    "number": 7,
    "atomic_mass": 14.007,
    "category": "no-metal",
    "melt": 63.15,
    "boil": 77.355,
    "density": 1.251,
    "discovered_by": "Daniel Rutherford",
    "group": 15,
    "period": 2,
    "xpos": 15,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Nitrogen_liquid.jpg/200px-Nitrogen_liquid.jpg", "title": "Nitrógeno líquido"},
    "desc_es": "Forma el 78% de la atmósfera terrestre. Gas incoloro. Esencial para ADN, proteínas y fertilizantes como amoníaco."
  },
  {
    "name": "Oxígeno",
    "symbol": "O",
    "number": 8,
    "atomic_mass": 15.999,
    "category": "no-metal",
    "melt": 54.36,
    "boil": 90.188,
    "density": 1.429,
    "discovered_by": "Joseph Priestley",
    "group": 16,
    "period": 2,
    "xpos": 16,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Oxygen_tank.jpg/200px-Oxygen_tank.jpg", "title": "Tanque de oxígeno"},
    "desc_es": "Forma el 21% del aire y el 46% de la corteza terrestre. Gas vital para la respiración. Usado en soldadura y medicina."
  },
  {
    "name": "Flúor",
    "symbol": "F",
    "number": 9,
    "atomic_mass": 18.998,
    "category": "no-metal",
    "melt": 53.48,
    "boil": 85.03,
    "density": 1.696,
    "discovered_by": "Henri Moissan",
    "group": 17,
    "period": 2,
    "xpos": 17,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Fluorine_gas.jpg/200px-Fluorine_gas.jpg", "title": "Flúor gaseoso"},
    "desc_es": "El elemento químico más electronegativo y reactivo. Se encuentra en fluorita. Usado en pastas dentales y compuestos antiadherentes como Teflon."
  },
  {
    "name": "Neón",
    "symbol": "Ne",
    "number": 10,
    "atomic_mass": 20.18,
    "category": "gas-noble",
    "melt": 24.56,
    "boil": 27.104,
    "density": 0.9002,
    "discovered_by": "William Ramsay",
    "group": 18,
    "period": 2,
    "xpos": 18,
    "ypos": 2,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Neon_glow_lamp.jpg/200px-Neon_glow_lamp.jpg", "title": "Lámpara de neón"},
    "desc_es": "Gas noble inerte con brillo rojo-anaranjado. Se encuentra en el aire (0.0018%). Usado en carteles luminosos y láseres."
  },
  {
    "name": "Sodio",
    "symbol": "Na",
    "number": 11,
    "atomic_mass": 22.99,
    "category": "alcalino",
    "melt": 370.87,
    "boil": 1156,
    "density": 0.968,
    "discovered_by": "Humphry Davy",
    "group": 1,
    "period": 3,
    "xpos": 1,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Sodium.jpg/200px-Sodium.jpg", "title": "Sodio metálico"},
    "desc_es": "Metal alcalino blando y reactivo con agua. Abundante en sal de mesa (NaCl). Usado en farolas de calle y compuestos químicos."
  },
  {
    "name": "Magnesio",
    "symbol": "Mg",
    "number": 12,
    "atomic_mass": 24.305,
    "category": "alcalinoterreo",
    "melt": 923,
    "boil": 1363,
    "density": 1.738,
    "discovered_by": "Joseph Black",
    "group": 2,
    "period": 3,
    "xpos": 2,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Magnesium_crystals.jpg/200px-Magnesium_crystals.jpg", "title": "Cristales de magnesio"},
    "desc_es": "Metal plateado ligero y combustible. Se encuentra en clorofila y dolomita. Usado en aleaciones para autos y fuegos artificiales."
  },
  {
    "name": "Aluminio",
    "symbol": "Al",
    "number": 13,
    "atomic_mass": 26.982,
    "category": "otro-metal",
    "melt": 933.47,
    "boil": 2792,
    "density": 2.7,
    "discovered_by": "Hans Christian Ørsted",
    "group": 13,
    "period": 3,
    "xpos": 13,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Aluminium_chunks.jpg/200px-Aluminium_chunks.jpg", "title": "Trozos de aluminio"},
    "desc_es": "Metal ligero, plateado y resistente a la corrosión. Tercero más abundante en la corteza. Usado en latas, aviones y cables."
  },
  {
    "name": "Silicio",
    "symbol": "Si",
    "number": 14,
    "atomic_mass": 28.085,
    "category": "metaloides",
    "melt": 1687,
    "boil": 3243,
    "density": 2.329,
    "discovered_by": "Jöns Jacob Berzelius",
    "group": 14,
    "period": 3,
    "xpos": 14,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Silicon-2.jpg/200px-Silicon-2.jpg", "title": "Silicio cristalino"},
    "desc_es": "Semimetal gris, segundo elemento más abundante en la Tierra. Base de la arena y cuarzo. Esencial para chips y semiconductores."
  },
  {
    "name": "Fósforo",
    "symbol": "P",
    "number": 15,
    "atomic_mass": 30.974,
    "category": "no-metal",
    "melt": 317.3,
    "boil": 553.7,
    "density": 1.82,
    "discovered_by": "Hennig Brand",
    "group": 15,
    "period": 3,
    "xpos": 15,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Phosphor_1.jpg/200px-Phosphor_1.jpg", "title": "Fósforo blanco"},
    "desc_es": "No metal reactivo, existe en blanco (tóxico) o rojo. Se encuentra en huesos y fertilizantes. Usado en cerillas y detergentes."
  },
  {
    "name": "Azufre",
    "symbol": "S",
    "number": 16,
    "atomic_mass": 32.06,
    "category": "no-metal",
    "melt": 388.36,
    "boil": 717.8,
    "density": 2.07,
    "discovered_by": "Antiguo",
    "group": 16,
    "period": 3,
    "xpos": 16,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Sulfur_sample.jpg/200px-Sulfur_sample.jpg", "title": "Muestra de azufre"},
    "desc_es": "No metal amarillo cristalino. Abundante en volcanes y yacimientos. Usado en ácido sulfúrico, goma y pólvora."
  },
  {
    "name": "Cloro",
    "symbol": "Cl",
    "number": 17,
    "atomic_mass": 35.45,
    "category": "no-metal",
    "melt": 171.6,
    "boil": 239.11,
    "density": 3.2,
    "discovered_by": "Carl Wilhelm Scheele",
    "group": 17,
    "period": 3,
    "xpos": 17,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Chlorine_gas.jpg/200px-Chlorine_gas.jpg", "title": "Cloro gaseoso"},
    "desc_es": "Gas tóxico amarillento-verdoso. Se encuentra en sal marina. Usado en desinfección de agua y producción de PVC."
  },
  {
    "name": "Argón",
    "symbol": "Ar",
    "number": 18,
    "atomic_mass": 39.948,
    "category": "gas-noble",
    "melt": 83.81,
    "boil": 87.302,
    "density": 1.784,
    "discovered_by": "William Ramsay",
    "group": 18,
    "period": 3,
    "xpos": 18,
    "ypos": 3,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Argon_glow.jpg/200px-Argon_glow.jpg", "title": "Brillo de argón"},
    "desc_es": "Gas noble inerte, 0.93% del aire. Se encuentra en la atmósfera. Usado en soldadura y bombillas incandescentes."
  },
  {
    "name": "Potasio",
    "symbol": "K",
    "number": 19,
    "atomic_mass": 39.098,
    "category": "alcalino",
    "melt": 336.7,
    "boil": 1032,
    "density": 0.862,
    "discovered_by": "Humphry Davy",
    "group": 1,
    "period": 4,
    "xpos": 1,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Potassium.jpg/200px-Potassium.jpg", "title": "Potasio metálico"},
    "desc_es": "Metal alcalino plateado y muy reactivo. Se encuentra en potasa y alimentos. Esencial para funciones nerviosas y fertilizantes."
  },
  {
    "name": "Calcio",
    "symbol": "Ca",
    "number": 20,
    "atomic_mass": 40.078,
    "category": "alcalinoterreo",
    "melt": 1115,
    "boil": 1768,
    "density": 1.55,
    "discovered_by": "Humphry Davy",
    "group": 2,
    "period": 4,
    "xpos": 2,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Calcium.jpg/200px-Calcium.jpg", "title": "Calcio metálico"},
    "desc_es": "Metal alcalinotérreo gris plateado. Abundante en huesos y conchas. Usado en cemento, yeso y suplementos dietéticos."
  },
  {
    "name": "Escandio",
    "symbol": "Sc",
    "number": 21,
    "atomic_mass": 44.956,
    "category": "metal-transicion",
    "melt": 1814,
    "boil": 3109,
    "density": 2.989,
    "discovered_by": "Lars Fredrik Nilson",
    "group": 3,
    "period": 4,
    "xpos": 3,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Scandium.jpg/200px-Scandium.jpg", "title": "Escandio"},
    "desc_es": "Metal de transición plateado. Raro en la corteza. Usado en aleaciones de aluminio para aerospacio."
  },
  {
    "name": "Titanio",
    "symbol": "Ti",
    "number": 22,
    "atomic_mass": 47.867,
    "category": "metal-transicion",
    "melt": 1941,
    "boil": 3560,
    "density": 4.506,
    "discovered_by": "William Gregor",
    "group": 4,
    "period": 4,
    "xpos": 4,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Titanium_crystal_bar.jpg/200px-Titanium_crystal_bar.jpg", "title": "Barra de titanio"},
    "desc_es": "Metal de transición fuerte y ligero. Abundante en rutilo. Usado en implantes médicos y aviones por su resistencia a la corrosión."
  },
  {
    "name": "Vanadio",
    "symbol": "V",
    "number": 23,
    "atomic_mass": 50.942,
    "category": "metal-transicion",
    "melt": 2202,
    "boil": 3690,
    "density": 6.0,
    "discovered_by": "Andrés Manuel del Río",
    "group": 5,
    "period": 4,
    "xpos": 5,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Vanadium.jpg/200px-Vanadium.jpg", "title": "Vanadio"},
    "desc_es": "Metal de transición gris plateado. Se encuentra en magnetita. Usado en acero para herramientas y baterías."
  },
  {
    "name": "Cromo",
    "symbol": "Cr",
    "number": 24,
    "atomic_mass": 51.996,
    "category": "metal-transicion",
    "melt": 2180,
    "boil": 2944,
    "density": 7.15,
    "discovered_by": "Louis Nicolas Vauquelin",
    "group": 6,
    "period": 4,
    "xpos": 6,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Chromium.jpg/200px-Chromium.jpg", "title": "Cromo metálico"},
    "desc_es": "Metal de transición duro y brillante. Se encuentra en cromita. Usado en acero inoxidable y cromado para autos."
  },
  {
    "name": "Manganeso",
    "symbol": "Mn",
    "number": 25,
    "atomic_mass": 54.938,
    "category": "metal-transicion",
    "melt": 1519,
    "boil": 2334,
    "density": 7.21,
    "discovered_by": "Johan Gottlieb Gahn",
    "group": 7,
    "period": 4,
    "xpos": 7,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Manganese.jpg/200px-Manganese.jpg", "title": "Manganeso"},
    "desc_es": "Metal de transición gris rosado. Abundante en pirolusita. Usado en acero para dureza y baterías alcalinas."
  },
  {
    "name": "Hierro",
    "symbol": "Fe",
    "number": 26,
    "atomic_mass": 55.845,
    "category": "metal-transicion",
    "melt": 1811,
    "boil": 3134,
    "density": 7.874,
    "discovered_by": "Antiguo",
    "group": 8,
    "period": 4,
    "xpos": 8,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Iron_electrolytic_and_1cm3_cube.jpg/200px-Iron_electrolytic_and_1cm3_cube.jpg", "title": "Hierro electrolítico"},
    "desc_es": "Metal de transición magnético y maleable. Cuarto elemento más abundante. Base del acero para construcción y herramientas."
  },
  {
    "name": "Cobalto",
    "symbol": "Co",
    "number": 27,
    "atomic_mass": 58.933,
    "category": "metal-transicion",
    "melt": 1768,
    "boil": 3200,
    "density": 8.86,
    "discovered_by": "Georg Brandt",
    "group": 9,
    "period": 4,
    "xpos": 9,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Cobalt.jpg/200px-Cobalt.jpg", "title": "Cobalto"},
    "desc_es": "Metal de transición duro y magnético. Se encuentra en cobaltita. Usado en imanes, aleaciones y baterías de litio."
  },
  {
    "name": "Níquel",
    "symbol": "Ni",
    "number": 28,
    "atomic_mass": 58.693,
    "category": "metal-transicion",
    "melt": 1728,
    "boil": 3003,
    "density": 8.908,
    "discovered_by": "Axel Fredrik Cronstedt",
    "group": 10,
    "period": 4,
    "xpos": 10,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nickel.jpg/200px-Nickel.jpg", "title": "Níquel"},
    "desc_es": "Metal de transición plateado con tinte dorado. Se encuentra en pentlandita. Usado en monedas, acero inoxidable y baterías."
  },
  {
    "name": "Cobre",
    "symbol": "Cu",
    "number": 29,
    "atomic_mass": 63.546,
    "category": "metal-transicion",
    "melt": 1357.77,
    "boil": 2839,
    "density": 8.933,
    "discovered_by": "Antiguo",
    "group": 11,
    "period": 4,
    "xpos": 11,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Copper_electrolytic.jpg/200px-Copper_electrolytic.jpg", "title": "Cobre electrolítico"},
    "desc_es": "Metal de transición rojizo excelente conductor. Abundante en calcopirita. Usado en cables eléctricos y tuberías."
  },
  {
    "name": "Zinc",
    "symbol": "Zn",
    "number": 30,
    "atomic_mass": 65.38,
    "category": "metal-transicion",
    "melt": 692.68,
    "boil": 1180,
    "density": 7.134,
    "discovered_by": "Antiguo",
    "group": 12,
    "period": 4,
    "xpos": 12,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Zinc.jpg/200px-Zinc.jpg", "title": "Zinc"},
    "desc_es": "Metal de transición azul plateado. Se encuentra en esfalerita. Usado en galvanizado para prevenir óxido y en baterías."
  },
  {
    "name": "Galio",
    "symbol": "Ga",
    "number": 31,
    "atomic_mass": 69.723,
    "category": "otro-metal",
    "melt": 302.91,
    "boil": 2676,
    "density": 5.91,
    "discovered_by": "Paul-Émile Lecoq de Boisbaudran",
    "group": 13,
    "period": 4,
    "xpos": 13,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Gallium_1.jpg/200px-Gallium_1.jpg", "title": "Galio líquido"},
    "desc_es": "Metal post-transición que se funde en la mano. Raro, en bauxita. Usado en LEDs y semiconductores."
  },
  {
    "name": "Germanio",
    "symbol": "Ge",
    "number": 32,
    "atomic_mass": 72.63,
    "category": "metaloides",
    "melt": 1211.4,
    "boil": 3106,
    "density": 5.323,
    "discovered_by": "Clemens Winkler",
    "group": 14,
    "period": 4,
    "xpos": 14,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Germanium.jpg/200px-Germanium.jpg", "title": "Germanio"},
    "desc_es": "Semimetal gris blanco. Se encuentra en argirodita. Usado en transistores y fibra óptica."
  },
  {
    "name": "Arsénico",
    "symbol": "As",
    "number": 33,
    "atomic_mass": 74.922,
    "category": "metaloides",
    "melt": 1090,
    "boil": 887,
    "density": 5.73,
    "discovered_by": "Antiguo",
    "group": 15,
    "period": 4,
    "xpos": 15,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Arsenic-4.jpg/200px-Arsenic-4.jpg", "title": "Arsénico gris"},
    "desc_es": "Semimetal tóxico gris. Se encuentra en mispickel. Usado en semiconductores y pesticidas (con precaución)."
  },
  {
    "name": "Selenio",
    "symbol": "Se",
    "number": 34,
    "atomic_mass": 78.971,
    "category": "no-metal",
    "melt": 494,
    "boil": 958,
    "density": 4.81,
    "discovered_by": "Jöns Jacob Berzelius",
    "group": 16,
    "period": 4,
    "xpos": 16,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Selenium.jpg/200px-Selenium.jpg", "title": "Selenio"},
    "desc_es": "No metal gris con propiedades metálicas. Subproducto del cobre. Usado en fotocopiadoras y suplementos nutricionales."
  },
  {
    "name": "Bromo",
    "symbol": "Br",
    "number": 35,
    "atomic_mass": 79.904,
    "category": "no-metal",
    "melt": 265.8,
    "boil": 331.9,
    "density": 3.1028,
    "discovered_by": "Antoine Jérôme Balard",
    "group": 17,
    "period": 4,
    "xpos": 17,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Bromine-sample.jpg/200px-Bromine-sample.jpg", "title": "Bromo líquido"},
    "desc_es": "Halonógeno líquido rojo volátil y tóxico. Se encuentra en aguas salobres. Usado en retardantes de llama y fotografía."
  },
  {
    "name": "Kriptón",
    "symbol": "Kr",
    "number": 36,
    "atomic_mass": 83.798,
    "category": "gas-noble",
    "melt": 115.78,
    "boil": 119.93,
    "density": 3.733,
    "discovered_by": "William Ramsay",
    "group": 18,
    "period": 4,
    "xpos": 18,
    "ypos": 4,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Krypton_liquid.jpg/200px-Krypton_liquid.jpg", "title": "Kriptón líquido"},
    "desc_es": "Gas noble incoloro, 1 ppm en aire. Se encuentra en la atmósfera. Usado en láseres y luces de aviación."
  },
  {
    "name": "Rubidio",
    "symbol": "Rb",
    "number": 37,
    "atomic_mass": 85.468,
    "category": "alcalino",
    "melt": 312.46,
    "boil": 961,
    "density": 1.532,
    "discovered_by": "Robert Bunsen",
    "group": 1,
    "period": 5,
    "xpos": 1,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Rubidium.jpg/200px-Rubidium.jpg", "title": "Rubidio"},
    "desc_es": "Metal alcalino plateado altamente reactivo. Raro, en lepidolita. Usado en relojes atómicos y células fotoeléctricas."
  },
  {
    "name": "Estroncio",
    "symbol": "Sr",
    "number": 38,
    "atomic_mass": 87.62,
    "category": "alcalinoterreo",
    "melt": 1050,
    "boil": 1650,
    "density": 2.64,
    "discovered_by": "Adair Crawford",
    "group": 2,
    "period": 5,
    "xpos": 2,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Strontium.jpg/200px-Strontium.jpg", "title": "Estroncio"},
    "desc_es": "Metal alcalinotérreo plateado amarillento. Se encuentra en celestita. Usado en fuegos artificiales (rojo) y aleaciones."
  },
  {
    "name": "Itrio",
    "symbol": "Y",
    "number": 39,
    "atomic_mass": 88.906,
    "category": "metal-transicion",
    "melt": 1799,
    "boil": 3611,
    "density": 4.472,
    "discovered_by": "Johan Gadolin",
    "group": 3,
    "period": 5,
    "xpos": 3,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Yttrium.jpg/200px-Yttrium.jpg", "title": "Itrio"},
    "desc_es": "Metal de transición plateado. Se encuentra en monacita. Usado en superaleaciones y fósforos para TVs."
  },
  {
    "name": "Circonio",
    "symbol": "Zr",
    "number": 40,
    "atomic_mass": 91.224,
    "category": "metal-transicion",
    "melt": 2128,
    "boil": 4682,
    "density": 6.52,
    "discovered_by": "Johan August Sefström",
    "group": 4,
    "period": 5,
    "xpos": 4,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Zirconium.jpg/200px-Zirconium.jpg", "title": "Circonio"},
    "desc_es": "Metal de transición gris plateado resistente a corrosión. En zircón. Usado en reactores nucleares y joyería."
  },
  {
    "name": "Niobio",
    "symbol": "Nb",
    "number": 41,
    "atomic_mass": 92.906,
    "category": "metal-transicion",
    "melt": 2750,
    "boil": 5017,
    "density": 8.57,
    "discovered_by": "Charles Hatchett",
    "group": 5,
    "period": 5,
    "xpos": 5,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Niobium.jpg/200px-Niobium.jpg", "title": "Niobio"},
    "desc_es": "Metal de transición gris brillante. En columbita. Usado en superaleaciones para turbinas de jet."
  },
  {
    "name": "Molibdeno",
    "symbol": "Mo",
    "number": 42,
    "atomic_mass": 95.95,
    "category": "metal-transicion",
    "melt": 2896,
    "boil": 4912,
    "density": 10.28,
    "discovered_by": "Carl Wilhelm Scheele",
    "group": 6,
    "period": 5,
    "xpos": 6,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Molybdenum.jpg/200px-Molybdenum.jpg", "title": "Molibdeno"},
    "desc_es": "Metal de transición plateado duro. En molibdenita. Usado en acero para herramientas y catalizadores."
  },
  {
    "name": "Tecnecio",
    "symbol": "Tc",
    "number": 43,
    "atomic_mass": 98,
    "category": "metal-transicion",
    "melt": 2430,
    "boil": 4538,
    "density": 11.5,
    "discovered_by": "Emilio Segrè",
    "group": 7,
    "period": 5,
    "xpos": 7,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Technetium.jpg/200px-Technetium.jpg", "title": "Tecnecio"},
    "desc_es": "Primer elemento sintético, radiactivo. No se encuentra natural. Usado en imágenes médicas (isótopo 99mTc)."
  },
  {
    "name": "Rutenio",
    "symbol": "Ru",
    "number": 44,
    "atomic_mass": 101.07,
    "category": "metal-transicion",
    "melt": 2607,
    "boil": 4423,
    "density": 12.45,
    "discovered_by": "Karl Ernst Claus",
    "group": 8,
    "period": 5,
    "xpos": 8,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Ruthenium.jpg/200px-Ruthenium.jpg", "title": "Rutenio"},
    "desc_es": "Metal de transición duro y raro. En platino. Usado en contactos eléctricos y catalizadores automotrices."
  },
  {
    "name": "Rodio",
    "symbol": "Rh",
    "number": 45,
    "atomic_mass": 102.91,
    "category": "metal-transicion",
    "melt": 2237,
    "boil": 3963,
    "density": 12.41,
    "discovered_by": "William Hyde Wollaston",
    "group": 9,
    "period": 5,
    "xpos": 9,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rhodium.jpg/200px-Rhodium.jpg", "title": "Rodio"},
    "desc_es": "Metal de transición plateado resistente a corrosión. Raro, en platino. Usado en convertidores catalíticos y joyería."
  },
  {
    "name": "Paladio",
    "symbol": "Pd",
    "number": 46,
    "atomic_mass": 106.42,
    "category": "metal-transicion",
    "melt": 1828.05,
    "boil": 3236,
    "density": 12.02,
    "discovered_by": "William Hyde Wollaston",
    "group": 10,
    "period": 5,
    "xpos": 10,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Palladium.jpg/200px-Palladium.jpg", "title": "Paladio"},
    "desc_es": "Metal de transición plateado que absorbe hidrógeno. En platino. Usado en catalizadores y joyería blanca."
  },
  {
    "name": "Plata",
    "symbol": "Ag",
    "number": 47,
    "atomic_mass": 107.87,
    "category": "metal-transicion",
    "melt": 1234.93,
    "boil": 2435,
    "density": 10.49,
    "discovered_by": "Antiguo",
    "group": 11,
    "period": 5,
    "xpos": 11,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Silver.jpg/200px-Silver.jpg", "title": "Plata"},
    "desc_es": "Metal de transición blanco brillante, mejor conductor. En galena argentífera. Usado en joyería, monedas y fotografía."
  },
  {
    "name": "Cadmio",
    "symbol": "Cd",
    "number": 48,
    "atomic_mass": 112.41,
    "category": "metal-transicion",
    "melt": 594.22,
    "boil": 1040,
    "density": 8.65,
    "discovered_by": "Stromeyer",
    "group": 12,
    "period": 5,
    "xpos": 12,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cadmium.jpg/200px-Cadmium.jpg", "title": "Cadmio"},
    "desc_es": "Metal de transición blando y tóxico. Subproducto del zinc. Usado en baterías Ni-Cd y pigmentos amarillos."
  },
  {
    "name": "Indio",
    "symbol": "In",
    "number": 49,
    "atomic_mass": 114.82,
    "category": "otro-metal",
    "melt": 429.75,
    "boil": 2566,
    "density": 7.31,
    "discovered_by": "Ferdinand Reich",
    "group": 13,
    "period": 5,
    "xpos": 13,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Indium.jpg/200px-Indium.jpg", "title": "Indio"},
    "desc_es": "Metal post-transición plateado maleable. Raro, en zinc. Usado en pantallas LCD y soldaduras."
  },
  {
    "name": "Estaño",
    "symbol": "Sn",
    "number": 50,
    "atomic_mass": 118.71,
    "category": "otro-metal",
    "melt": 505.08,
    "boil": 2875,
    "density": 7.31,
    "discovered_by": "Antiguo",
    "group": 14,
    "period": 5,
    "xpos": 14,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Tin.jpg/200px-Tin.jpg", "title": "Estaño"},
    "desc_es": "Metal post-transición blanco plateado. En casiterita. Usado en soldadura, latas y bronce."
  },
  {
    "name": "Antimonio",
    "symbol": "Sb",
    "number": 51,
    "atomic_mass": 121.76,
    "category": "metaloides",
    "melt": 903.78,
    "boil": 1908,
    "density": 6.697,
    "discovered_by": "Antiguo",
    "group": 15,
    "period": 5,
    "xpos": 15,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Antimony.jpg/200px-Antimony.jpg", "title": "Antimonio"},
    "desc_es": "Semimetal gris quebradizo. En estibnita. Usado en aleaciones, retardantes de llama y semiconductores."
  },
  {
    "name": "Telurio",
    "symbol": "Te",
    "number": 52,
    "atomic_mass": 127.6,
    "category": "metaloides",
    "melt": 722.66,
    "boil": 1261,
    "density": 6.24,
    "discovered_by": "Franz-Joseph Müller von Reichenstein",
    "group": 16,
    "period": 5,
    "xpos": 16,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Tellurium.jpg/200px-Tellurium.jpg", "title": "Telurio"},
    "desc_es": "Semimetal blanco plateado, raro y tóxico. Subproducto del cobre. Usado en aleaciones y paneles solares."
  },
  {
    "name": "Yodo",
    "symbol": "I",
    "number": 53,
    "atomic_mass": 126.9,
    "category": "no-metal",
    "melt": 386.85,
    "boil": 457.4,
    "density": 4.933,
    "discovered_by": "Bernard Courtois",
    "group": 17,
    "period": 5,
    "xpos": 17,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Iodine-sample.jpg/200px-Iodine-sample.jpg", "title": "Cristales de yodo"},
    "desc_es": "Halonógeno violeta-negro volátil. En algas marinas. Esencial para tiroides; usado en desinfectantes."
  },
  {
    "name": "Xenón",
    "symbol": "Xe",
    "number": 54,
    "atomic_mass": 131.29,
    "category": "gas-noble",
    "melt": 161.4,
    "boil": 165.051,
    "density": 5.851,
    "discovered_by": "William Ramsay",
    "group": 18,
    "period": 5,
    "xpos": 18,
    "ypos": 5,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Xenon_liquid.jpg/200px-Xenon_liquid.jpg", "title": "Xenón líquido"},
    "desc_es": "Gas noble incoloro, 0.09 ppm en aire. Se encuentra en atmósfera. Usado en lámparas de flash y anestésicos."
  },
  {
    "name": "Cesio",
    "symbol": "Cs",
    "number": 55,
    "atomic_mass": 132.91,
    "category": "alcalino",
    "melt": 301.7,
    "boil": 944,
    "density": 1.93,
    "discovered_by": "Gustav Kirchhoff",
    "group": 1,
    "period": 6,
    "xpos": 1,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Caesium.jpg/200px-Caesium.jpg", "title": "Cesio"},
    "desc_es": "Metal alcalino dorado, más blando. Raro, en pollucita. Usado en relojes atómicos y perforación petrolera."
  },
  {
    "name": "Bario",
    "symbol": "Ba",
    "number": 56,
    "atomic_mass": 137.33,
    "category": "alcalinoterreo",
    "melt": 1000,
    "boil": 2118,
    "density": 3.51,
    "discovered_by": "Humphry Davy",
    "group": 2,
    "period": 6,
    "xpos": 2,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Barium.jpg/200px-Barium.jpg", "title": "Bario"},
    "desc_es": "Metal alcalinotérreo plateado reactivo. En baritina. Usado en rayos X (sulfato) y fuegos artificiales."
  },
  {
    "name": "Lantano",
    "symbol": "La",
    "number": 57,
    "atomic_mass": 138.91,
    "category": "lantanidos",
    "melt": 1193,
    "boil": 3737,
    "density": 6.162,
    "discovered_by": "Carl Gustaf Mosander",
    "group": 3,
    "period": 6,
    "xpos": 3,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Lanthanum.jpg/200px-Lanthanum.jpg", "title": "Lantano"},
    "desc_es": "Lantánido plateado maleable. En monacita. Usado en baterías NiMH y óptica."
  },
  {
    "name": "Hafnio",
    "symbol": "Hf",
    "number": 72,
    "atomic_mass": 178.49,
    "category": "metal-transicion",
    "melt": 2506,
    "boil": 4876,
    "density": 13.31,
    "discovered_by": "Dirac Costa",
    "group": 4,
    "period": 6,
    "xpos": 4,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Hafnium.jpg/200px-Hafnium.jpg", "title": "Hafnio"},
    "desc_es": "Metal de transición similar al zirconio. Raro. Usado en reactores nucleares y chips."
  },
  {
    "name": "Tantalio",
    "symbol": "Ta",
    "number": 73,
    "atomic_mass": 180.95,
    "category": "metal-transicion",
    "melt": 3290,
    "boil": 5731,
    "density": 16.65,
    "discovered_by": "Anders Gustaf Ekeberg",
    "group": 5,
    "period": 6,
    "xpos": 5,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Tantalum.jpg/200px-Tantalum.jpg", "title": "Tantalio"},
    "desc_es": "Metal de transición duro y ácido-resistente. En tantalita. Usado en capacitores y cirugía."
  },
  {
    "name": "Wolframio",
    "symbol": "W",
    "number": 74,
    "atomic_mass": 183.84,
    "category": "metal-transicion",
    "melt": 3695,
    "boil": 6203,
    "density": 19.25,
    "discovered_by": "Fausto y Juan Elhuyar",
    "group": 6,
    "period": 6,
    "xpos": 6,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Tungsten.jpg/200px-Tungsten.jpg", "title": "Wolframio"},
    "desc_es": "Metal de transición con punto de fusión más alto. En wolframita. Usado en filamentos de bombillas y brocas."
  },
  {
    "name": "Renio",
    "symbol": "Re",
    "number": 75,
    "atomic_mass": 186.21,
    "category": "metal-transicion",
    "melt": 3459,
    "boil": 5869,
    "density": 21.02,
    "discovered_by": "Walter Noddack",
    "group": 7,
    "period": 6,
    "xpos": 7,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Rhenium.jpg/200px-Rhenium.jpg", "title": "Renio"},
    "desc_es": "Metal de transición raro y denso. En molibdenita. Usado en superaleaciones para motores de jet."
  },
  {
    "name": "Osmio",
    "symbol": "Os",
    "number": 76,
    "atomic_mass": 190.23,
    "category": "metal-transicion",
    "melt": 3306,
    "boil": 4506,
    "density": 22.59,
    "discovered_by": "Smithson Tennant",
    "group": 8,
    "period": 6,
    "xpos": 8,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Osmium.jpg/200px-Osmium.jpg", "title": "Osmio"},
    "desc_es": "Metal de transición más denso, tóxico. Raro. Usado en puntas de pluma y aleaciones duras."
  },
  {
    "name": "Iridio",
    "symbol": "Ir",
    "number": 77,
    "atomic_mass": 192.22,
    "category": "metal-transicion",
    "melt": 2719,
    "boil": 4700,
    "density": 22.56,
    "discovered_by": "Smithson Tennant",
    "group": 9,
    "period": 6,
    "xpos": 9,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Iridium.jpg/200px-Iridium.jpg", "title": "Iridio"},
    "desc_es": "Metal de transición blanco plateado muy duro. Raro, en iridios. Usado en bujías y contactos eléctricos."
  },
  {
    "name": "Platino",
    "symbol": "Pt",
    "number": 78,
    "atomic_mass": 195.08,
    "category": "metal-transicion",
    "melt": 2041.4,
    "boil": 4098,
    "density": 21.45,
    "discovered_by": "Antonio de Ulloa",
    "group": 10,
    "period": 6,
    "xpos": 10,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Platinum-crystal.jpg/200px-Platinum-crystal.jpg", "title": "Cristal de platino"},
    "desc_es": "Metal de transición gris plateado inerte. En depósitos aluviales. Usado en joyería, catalizadores y termopares."
  },
  {
    "name": "Oro",
    "symbol": "Au",
    "number": 79,
    "atomic_mass": 196.97,
    "category": "metal-transicion",
    "melt": 1337.33,
    "boil": 3243,
    "density": 19.3,
    "discovered_by": "Antiguo",
    "group": 11,
    "period": 6,
    "xpos": 11,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Gold_nugget.jpg/200px-Gold_nugget.jpg", "title": "Pepita de oro"},
    "desc_es": "Metal de transición amarillo brillante, no oxidable. En vetas de cuarzo. Usado en joyería, electrónica y moneda."
  },
  {
    "name": "Mercurio",
    "symbol": "Hg",
    "number": 80,
    "atomic_mass": 200.59,
    "category": "metal-transicion",
    "melt": -38.83,
    "boil": 630.63,
    "density": 13.534,
    "discovered_by": "Antiguo",
    "group": 12,
    "period": 6,
    "xpos": 12,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Mercury_droplet.jpg/200px-Mercury_droplet.jpg", "title": "Gota de mercurio"},
    "desc_es": "Metal de transición líquido a temperatura ambiente, tóxico. En cinabrio. Usado en termómetros y lámparas (ahora restringido)."
  },
  {
    "name": "Talio",
    "symbol": "Tl",
    "number": 81,
    "atomic_mass": 204.38,
    "category": "otro-metal",
    "melt": 577,
    "boil": 1746,
    "density": 11.85,
    "discovered_by": "William Crookes",
    "group": 13,
    "period": 6,
    "xpos": 13,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Thallium.jpg/200px-Thallium.jpg", "title": "Talio"},
    "desc_es": "Metal post-transición blando y tóxico. Raro. Usado en vidrios ópticos y electrónica."
  },
  {
    "name": "Plomo",
    "symbol": "Pb",
    "number": 82,
    "atomic_mass": 207.2,
    "category": "otro-metal",
    "melt": 600.61,
    "boil": 2022,
    "density": 11.34,
    "discovered_by": "Antiguo",
    "group": 14,
    "period": 6,
    "xpos": 14,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Lead-1.jpg/200px-Lead-1.jpg", "title": "Plomo"},
    "desc_es": "Metal post-transición gris azulado tóxico. En galena. Usado en baterías y blindaje contra radiación."
  },
  {
    "name": "Bismuto",
    "symbol": "Bi",
    "number": 83,
    "atomic_mass": 208.98,
    "category": "otro-metal",
    "melt": 544.7,
    "boil": 1837,
    "density": 9.78,
    "discovered_by": "Georgius Agricola",
    "group": 15,
    "period": 6,
    "xpos": 15,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bismuth_crystal.jpg/200px-Bismuth_crystal.jpg", "title": "Cristal de bismuto"},
    "desc_es": "Metal post-transición rosado diamagnético. En bismutinita. Usado en medicamentos para estómago y cosméticos."
  },
  {
    "name": "Polonio",
    "symbol": "Po",
    "number": 84,
    "atomic_mass": 209,
    "category": "metaloides",
    "melt": 527,
    "boil": 1235,
    "density": 9.32,
    "discovered_by": "Marie Curie",
    "group": 16,
    "period": 6,
    "xpos": 16,
    "ypos": 6,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Polonium.jpg/200px-Polonium.jpg", "title": "Polonio"},
    "desc_es": "Semimetal radiactivo raro y tóxico. Subproducto del uranio. Usado en eliminadores de estática."
  },
  {
    "name": "Astato",
    "symbol": "At",
    "number": 85,
    "atomic_mass": 210,
    "category": "no-metal",
    "melt": 575,
    "boil": 610,
    "density": 6.35,
    "discovered_by": "Dale R. Corson",
    "group": 17,
    "period": 6,
    "xpos": 17,
    "ypos": 6,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Halonógeno radiactivo sintético, el más raro. No se encuentra natural. Potencial en terapia contra cáncer."
  },
  {
    "name": "Radón",
    "symbol": "Rn",
    "number": 86,
    "atomic_mass": 222,
    "category": "gas-noble",
    "melt": 202,
    "boil": 211.5,
    "density": 9.73,
    "discovered_by": "Ernest Rutherford",
    "group": 18,
    "period": 6,
    "xpos": 18,
    "ypos": 6,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Gas noble radiactivo incoloro, causa de cáncer de pulmón. Subproducto del radio en suelos."
  },
  {
    "name": "Francio",
    "symbol": "Fr",
    "number": 87,
    "atomic_mass": 223,
    "category": "alcalino",
    "melt": 300,
    "boil": 950,
    "density": 1.87,
    "discovered_by": "Marguerite Perey",
    "group": 1,
    "period": 7,
    "xpos": 1,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Metal alcalino radiactivo, el más inestable. Sintético, no se encuentra. Propiedades teóricas similares al cesio."
  },
  {
    "name": "Radio",
    "symbol": "Ra",
    "number": 88,
    "atomic_mass": 226,
    "category": "alcalinoterreo",
    "melt": 1233,
    "boil": 1412,
    "density": 5,
    "discovered_by": "Marie Curie",
    "group": 2,
    "period": 7,
    "xpos": 2,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Metal alcalinotérreo radiactivo blanco. En uranio. Históricamente usado en pinturas luminosas, ahora peligroso."
  },
  {
    "name": "Actinio",
    "symbol": "Ac",
    "number": 89,
    "atomic_mass": 227,
    "category": "actínidos",
    "melt": 1051,
    "boil": 3198,
    "density": 10.07,
    "discovered_by": "André-Louis Debierne",
    "group": 3,
    "period": 7,
    "xpos": 3,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido radiactivo plateado. Subproducto del uranio. Usado en investigación nuclear."
  },
  {
    "name": "Torio",
    "symbol": "Th",
    "number": 90,
    "atomic_mass": 232.04,
    "category": "actínidos",
    "melt": 2023,
    "boil": 5061,
    "density": 11.72,
    "discovered_by": "Jöns Jakob Berzelius",
    "group": 4,
    "period": 7,
    "xpos": 4,
    "ypos": 10,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Thorium.jpg/200px-Thorium.jpg", "title": "Torio"},
    "desc_es": "Actínido radiactivo blanco, abundante. En monacita. Potencial combustible nuclear alternativo."
  },
  {
    "name": "Protactinio",
    "symbol": "Pa",
    "number": 91,
    "atomic_mass": 231.04,
    "category": "actínidos",
    "melt": 1841,
    "boil": 4300,
    "density": 15.37,
    "discovered_by": "William Crookes",
    "group": 5,
    "period": 7,
    "xpos": 5,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido radiactivo raro y tóxico. Subproducto del uranio. Poco uso práctico."
  },
  {
    "name": "Uranio",
    "symbol": "U",
    "number": 92,
    "atomic_mass": 238.03,
    "category": "actínidos",
    "melt": 1408,
    "boil": 4404,
    "density": 19.1,
    "discovered_by": "Martin Klaproth",
    "group": 6,
    "period": 7,
    "xpos": 6,
    "ypos": 10,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Uranium_ore.jpg/200px-Uranium_ore.jpg", "title": "Mineral de uranio"},
    "desc_es": "Actínido radiactivo denso. En pechblenda. Combustible para reactores nucleares y armas."
  },
  {
    "name": "Neptunio",
    "symbol": "Np",
    "number": 93,
    "atomic_mass": 237,
    "category": "actínidos",
    "melt": 917,
    "boil": 4174,
    "density": 20.25,
    "discovered_by": "Edwin McMillan",
    "group": 7,
    "period": 7,
    "xpos": 7,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo. Producido en reactores. Usado en detectores de neutrones."
  },
  {
    "name": "Plutonio",
    "symbol": "Pu",
    "number": 94,
    "atomic_mass": 244,
    "category": "actínidos",
    "melt": 912.5,
    "boil": 3501,
    "density": 19.86,
    "discovered_by": "Glenn T. Seaborg",
    "group": 8,
    "period": 7,
    "xpos": 8,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético tóxico, fissionable. Producido en reactores. Usado en armas nucleares y generadores espaciales."
  },
  {
    "name": "Americio",
    "symbol": "Am",
    "number": 95,
    "atomic_mass": 243,
    "category": "actínidos",
    "melt": 1449,
    "boil": 2880,
    "density": 13.67,
    "discovered_by": "Glenn T. Seaborg",
    "group": 9,
    "period": 7,
    "xpos": 9,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo. De plutonio. Usado en detectores de humo y medición de espesor."
  },
  {
    "name": "Curio",
    "symbol": "Cm",
    "number": 96,
    "atomic_mass": 247,
    "category": "actínidos",
    "melt": 1345,
    "boil": 3100,
    "density": 13.51,
    "discovered_by": "Glenn T. Seaborg",
    "group": 10,
    "period": 7,
    "xpos": 10,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo. De plutonio. Usado en investigación y generadores termoeléctricos espaciales."
  },
  {
    "name": "Berkelio",
    "symbol": "Bk",
    "number": 97,
    "atomic_mass": 247,
    "category": "actínidos",
    "melt": 1259,
    "boil": null,
    "density": 14.78,
    "discovered_by": "Stanley G. Thompson",
    "group": 11,
    "period": 7,
    "xpos": 11,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo de vida corta. Producido en aceleradores. Solo para investigación científica."
  },
  {
    "name": "Californio",
    "symbol": "Cf",
    "number": 98,
    "atomic_mass": 251,
    "category": "actínidos",
    "melt": 1173,
    "boil": null,
    "density": 15.1,
    "discovered_by": "Stanley G. Thompson",
    "group": 12,
    "period": 7,
    "xpos": 12,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo. Producido en Berkeley. Usado en fuentes de neutrones portátiles."
  },
  {
    "name": "Einstenio",
    "symbol": "Es",
    "number": 99,
    "atomic_mass": 252,
    "category": "actínidos",
    "melt": 1133,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 13,
    "period": 7,
    "xpos": 13,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético de vida corta. De explosiones nucleares. Solo para estudio de propiedades químicas."
  },
  {
    "name": "Fermio",
    "symbol": "Fm",
    "number": 100,
    "atomic_mass": 257,
    "category": "actínidos",
    "melt": 1800,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 14,
    "period": 7,
    "xpos": 14,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético radiactivo. De pruebas de bombas H. Investigación pura."
  },
  {
    "name": "Mendelevio",
    "symbol": "Md",
    "number": 101,
    "atomic_mass": 258,
    "category": "actínidos",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 15,
    "period": 7,
    "xpos": 15,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético de pocos átomos. Producido en ciclotrón. Estudio de transuránicos."
  },
  {
    "name": "Nobelio",
    "symbol": "No",
    "number": 102,
    "atomic_mass": 259,
    "category": "actínidos",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 16,
    "period": 7,
    "xpos": 16,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Actínido sintético inestable. Nombrado por Alfred Nobel. Solo átomos individuales para experimentos."
  },
  {
    "name": "Laurencio",
    "symbol": "Lr",
    "number": 103,
    "atomic_mass": 266,
    "category": "actínidos",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Georgy Flerov",
    "group": 17,
    "period": 7,
    "xpos": 17,
    "ypos": 10,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Último actínido sintético, radiactivo extremo. Producido en Dubna. Investigación fundamental."
  },
  {
    "name": "Rutherfordio",
    "symbol": "Rf",
    "number": 104,
    "atomic_mass": 267,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 4,
    "period": 7,
    "xpos": 4,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Elemento superpesado sintético. Nombrado por Rutherford. Propiedades teóricas, vida media segundos."
  },
  {
    "name": "Dubnio",
    "symbol": "Db",
    "number": 105,
    "atomic_mass": 268,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 5,
    "period": 7,
    "xpos": 5,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético inestable. De Dubna. Estudio de isla de estabilidad."
  },
  {
    "name": "Seaborgio",
    "symbol": "Sg",
    "number": 106,
    "atomic_mass": 269,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Albert Ghiorso",
    "group": 6,
    "period": 7,
    "xpos": 6,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Seaborg. Vida media muy corta."
  },
  {
    "name": "Bohrio",
    "symbol": "Bh",
    "number": 107,
    "atomic_mass": 270,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Peter Armbruster",
    "group": 7,
    "period": 7,
    "xpos": 7,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Bohr. Investigación en GSI."
  },
  {
    "name": "Hassio",
    "symbol": "Hs",
    "number": 108,
    "atomic_mass": 269,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Peter Armbruster",
    "group": 8,
    "period": 7,
    "xpos": 8,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Hass. Propiedades químicas estudiadas recientemente."
  },
  {
    "name": "Meitnerio",
    "symbol": "Mt",
    "number": 109,
    "atomic_mass": 278,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Peter Armbruster",
    "group": 9,
    "period": 7,
    "xpos": 9,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Meitner. Vida media milisegundos."
  },
  {
    "name": "Darmstatio",
    "symbol": "Ds",
    "number": 110,
    "atomic_mass": 281,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Sigurd Hofmann",
    "group": 10,
    "period": 7,
    "xpos": 10,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. De Darmstadt. Estudio de reacciones químicas."
  },
  {
    "name": "Roentgenio",
    "symbol": "Rg",
    "number": 111,
    "atomic_mass": 282,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Sigurd Hofmann",
    "group": 11,
    "period": 7,
    "xpos": 11,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético volátil. Nombrado por Röntgen. Primer gas noble metálico teórico."
  },
  {
    "name": "Copernicio",
    "symbol": "Cn",
    "number": 112,
    "atomic_mass": 285,
    "category": "metal-transicion",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Sigurd Hofmann",
    "group": 12,
    "period": 7,
    "xpos": 12,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Copérnico. Posiblemente líquido a temperatura ambiente."
  },
  {
    "name": "Nihonio",
    "symbol": "Nh",
    "number": 113,
    "atomic_mass": 286,
    "category": "otro-metal",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Kōsuke Morita",
    "group": 13,
    "period": 7,
    "xpos": 13,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Nihon (Japón). Estudio de propiedades metálicas."
  },
  {
    "name": "Flerovio",
    "symbol": "Fl",
    "number": 114,
    "atomic_mass": 289,
    "category": "otro-metal",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 14,
    "period": 7,
    "xpos": 14,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Flerov. Posible semimetal."
  },
  {
    "name": "Moscovio",
    "symbol": "Mc",
    "number": 115,
    "atomic_mass": 290,
    "category": "otro-metal",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 15,
    "period": 7,
    "xpos": 15,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Moscú. Propiedades volátiles."
  },
  {
    "name": "Livermorio",
    "symbol": "Lv",
    "number": 116,
    "atomic_mass": 293,
    "category": "otro-metal",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 16,
    "period": 7,
    "xpos": 16,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superpesado sintético. Nombrado por Livermore. Posible gas noble metálico."
  },
  {
    "name": "Teneso",
    "symbol": "Ts",
    "number": 117,
    "atomic_mass": 294,
    "category": "no-metal",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 17,
    "period": 7,
    "xpos": 17,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Superhalógeno sintético. Nombrado por Tennessee. Muy reactivo teóricamente."
  },
  {
    "name": "Oganesón",
    "symbol": "Og",
    "number": 118,
    "atomic_mass": 294,
    "category": "gas-noble",
    "melt": null,
    "boil": null,
    "density": null,
    "discovered_by": "Yuri Oganessian",
    "group": 18,
    "period": 7,
    "xpos": 18,
    "ypos": 7,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Gas noble superpesado sintético. Nombrado por Oganessian. Posiblemente sólido, no inerte."
  }
  // Nota: Para los lantánidos (57-71), se colocan en una fila separada en el grid (ypos=9). Agrega posiciones xpos correspondientes en script.js si necesitas ajustar.
  // Lantánidos ejemplo (agrega el resto similar):
  , {
    "name": "Cerio",
    "symbol": "Ce",
    "number": 58,
    "atomic_mass": 140.12,
    "category": "lantanidos",
    "melt": 1068,
    "boil": 3716,
    "density": 6.77,
    "discovered_by": "Jöns Jacob Berzelius",
    "group": 3,
    "period": 6,
    "xpos": 4,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Cerium.jpg/200px-Cerium.jpg", "title": "Cerio"},
    "desc_es": "Lantánido plateado usado en catalizadores automotrices y pulido de vidrio."
  },
  {
    "name": "Praseodimio",
    "symbol": "Pr",
    "number": 59,
    "atomic_mass": 140.91,
    "category": "lantanidos",
    "melt": 1208,
    "boil": 3520,
    "density": 6.77,
    "discovered_by": "Didier Perrier",
    "group": 3,
    "period": 6,
    "xpos": 5,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Praseodymium.jpg/200px-Praseodymium.jpg", "title": "Praseodimio"},
    "desc_es": "Lantánido verde usado en aleaciones magnéticas y cerámicas."
  },
  {
    "name": "Neodimio",
    "symbol": "Nd",
    "number": 60,
    "atomic_mass": 144.24,
    "category": "lantanidos",
    "melt": 1297,
    "boil": 3342,
    "density": 7.01,
    "discovered_by": "Carl Auer von Welsbach",
    "group": 3,
    "period": 6,
    "xpos": 6,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Neodymium.jpg/200px-Neodymium.jpg", "title": "Neodimio"},
    "desc_es": "Lantánido usado en imanes potentes para motores eléctricos y auriculares."
  },
  {
    "name": "Prometio",
    "symbol": "Pm",
    "number": 61,
    "atomic_mass": 145,
    "category": "lantanidos",
    "melt": 1315,
    "boil": 3527,
    "density": 7.26,
    "discovered_by": "Jacob A. Marinsky",
    "group": 3,
    "period": 6,
    "xpos": 7,
    "ypos": 9,
    "image": {"url": "", "title": "No disponible"},
    "desc_es": "Lantánido radiactivo sintético. Usado en medidores de espesor."
  },
  {
    "name": "Samario",
    "symbol": "Sm",
    "number": 62,
    "atomic_mass": 150.36,
    "category": "lantanidos",
    "melt": 1345,
    "boil": 2173,
    "density": 7.52,
    "discovered_by": "Paul Émile Lecoq de Boisbaudran",
    "group": 3,
    "period": 6,
    "xpos": 8,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Samarium.jpg/200px-Samarium.jpg", "title": "Samario"},
    "desc_es": "Lantánido plateado usado en imanes y reactores nucleares."
  },
  {
    "name": "Europio",
    "symbol": "Eu",
    "number": 63,
    "atomic_mass": 151.96,
    "category": "lantanidos",
    "melt": 1099,
    "boil": 1802,
    "density": 5.24,
    "discovered_by": "Eugène-Anatole Demarçay",
    "group": 3,
    "period": 6,
    "xpos": 9,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Europium.jpg/200px-Europium.jpg", "title": "Europio"},
    "desc_es": "Lantánido suave usado en fósforos rojos para TVs y lámparas."
  },
  {
    "name": "Gadolinio",
    "symbol": "Gd",
    "number": 64,
    "atomic_mass": 157.25,
    "category": "lantanidos",
    "melt": 1585,
    "boil": 3546,
    "density": 7.9,
    "discovered_by": "Johan Gadolin",
    "group": 3,
    "period": 6,
    "xpos": 10,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Gadolinium.jpg/200px-Gadolinium.jpg", "title": "Gadolinio"},
    "desc_es": "Lantánido magnético usado en MRI y memorias de burbuja."
  },
  {
    "name": "Terbio",
    "symbol": "Tb",
    "number": 65,
    "atomic_mass": 158.93,
    "category": "lantanidos",
    "melt": 1630,
    "boil": 3396,
    "density": 8.23,
    "discovered_by": "Carl Gustaf Mosander",
    "group": 3,
    "period": 6,
    "xpos": 11,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Terbium.jpg/200px-Terbium.jpg", "title": "Terbio"},
    "desc_es": "Lantánido usado en fósforos verdes y actuadores piezoeléctricos."
  },
  {
    "name": "Disprosio",
    "symbol": "Dy",
    "number": 66,
    "atomic_mass": 162.5,
    "category": "lantanidos",
    "melt": 1680,
    "boil": 2840,
    "density": 8.55,
    "discovered_by": "Paul Émile Lecoq de Boisbaudran",
    "group": 3,
    "period": 6,
    "xpos": 12,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Dysprosium.jpg/200px-Dysprosium.jpg", "title": "Disprosio"},
    "desc_es": "Lantánido plateado usado en láseres y discos duros."
  },
  {
    "name": "Holmio",
    "symbol": "Ho",
    "number": 67,
    "atomic_mass": 164.93,
    "category": "lantanidos",
    "melt": 1737,
    "boil": 4167,
    "density": 8.79,
    "discovered_by": "Per Teodor Cleve",
    "group": 3,
    "period": 6,
    "xpos": 13,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Holmium.jpg/200px-Holmium.jpg", "title": "Holmio"},
    "desc_es": "Lantánido usado en imanes y calibración de espectrómetros."
  },
  {
    "name": "Erbio",
    "symbol": "Er",
    "number": 68,
    "atomic_mass": 167.26,
    "category": "lantanidos",
    "melt": 1802,
    "boil": null,
    "density": 9.066,
    "discovered_by": "Carl Gustaf Mosander",
    "group": 3,
    "period": 6,
    "xpos": 14,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Erbium.jpg/200px-Erbium.jpg", "title": "Erbio"},
    "desc_es": "Lantánido rosado usado en fibra óptica y láseres de YAG."
  },
  {
    "name": "Tulio",
    "symbol": "Tm",
    "number": 69,
    "atomic_mass": 168.93,
    "category": "lantanidos",
    "melt": 1818,
    "boil": 2223,
    "density": 9.32,
    "discovered_by": "Per Teodor Cleve",
    "group": 3,
    "period": 6,
    "xpos": 15,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Thulium.jpg/200px-Thulium.jpg", "title": "Tulio"},
    "desc_es": "Lantánido más raro en tierra. Usado en rayos X portátiles."
  },
  {
    "name": "Iterbio",
    "symbol": "Yb",
    "number": 70,
    "atomic_mass": 173.05,
    "category": "lantanidos",
    "melt": 1097,
    "boil": 1469,
    "density": 6.965,
    "discovered_by": "Georges Urbain",
    "group": 3,
    "period": 6,
    "xpos": 16,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Ytterbium-2.jpg/200px-Ytterbium-2.jpg", "title": "Iterbio"},
    "desc_es": "Lantánido usado en relojes atómicos y aleaciones dentales."
  },
  {
    "name": "Lutecio",
    "symbol": "Lu",
    "number": 71,
    "atomic_mass": 174.97,
    "category": "lantanidos",
    "melt": 1925,
    "boil": 3675,
    "density": 9.84,
    "discovered_by": "Georges Urbain",
    "group": 3,
    "period": 6,
    "xpos": 17,
    "ypos": 9,
    "image": {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Lutetium.jpg/200px-Lutetium.jpg", "title": "Lutecio"},
    "desc_es": "Lantánido más denso. Usado en catalizadores y datación geológica."
  }
];
